# Generated by Django 3.2 on 2021-04-17 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=12)),
                ('b_title', models.CharField(max_length=15)),
                ('b_text', models.TextField()),
                ('b_datetime', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
