# Generated by Django 3.2 on 2021-08-01 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrcSido',
            fields=[
                ('doro_cd', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('doro_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('doro_roma', models.CharField(blank=True, max_length=80, null=True)),
                ('dong_one_cd', models.CharField(max_length=2)),
                ('sido_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('sido_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('sigungu_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('sigungu_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_type', models.CharField(blank=True, max_length=1, null=True)),
                ('dong_cd', models.CharField(blank=True, max_length=3, null=True)),
                ('is_use', models.CharField(blank=True, max_length=1, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('change_content', models.CharField(blank=True, max_length=14, null=True)),
                ('from_date', models.CharField(blank=True, max_length=8, null=True)),
                ('to_date', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'entrc_sido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KoreaDongPgTbl',
            fields=[
                ('adm_dr_cd', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sido_nm', models.CharField(max_length=45)),
                ('sigungu_nm', models.CharField(max_length=45)),
                ('adm_dr_nm', models.CharField(max_length=45)),
                ('sido_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('sigungu_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('adm_dr_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('sido_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('sigungu_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('adm_dr_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('sido_cd', models.CharField(max_length=2)),
                ('sigungu_cd', models.CharField(max_length=5)),
                ('adm_dr_cd2', models.CharField(max_length=11)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'korea_dong_pg_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('p_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_image', imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20210801/')),
                ('p_filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_locType1', models.CharField(default='', max_length=12)),
                ('b_locType2', models.CharField(default='', max_length=12)),
                ('b_locType3', models.CharField(default='', max_length=12, null=True)),
                ('b_theme', models.CharField(default='', max_length=12, null=True)),
                ('b_title', models.CharField(max_length=15)),
                ('b_text', models.TextField()),
                ('b_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('b_del', models.CharField(default='N', max_length=1)),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('p_id', models.ForeignKey(db_column='p_id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='posts.photo')),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('lp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lp_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('lp_del', models.CharField(default='N', max_length=1)),
                ('b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
