# Generated by Django 3.2.5 on 2021-09-21 18:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20210921/'),
        ),
    ]
