# Generated by Django 3.2.5 on 2021-09-22 09:21

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_photo_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_hash_tag_1',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_hash_tag_2',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20210922/'),
        ),
    ]
