# Generated by Django 3.2 on 2021-08-15 18:30

import datetime
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_photo_p_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='p_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20210815/'),
        ),
    ]
