# Generated by Django 3.2 on 2022-01-08 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_photo_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220108/'),
        ),
        migrations.CreateModel(
            name='postComment',
            fields=[
                ('pc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pc_comment', models.TextField()),
                ('pc_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('pc_del', models.CharField(default='N', max_length=1)),
                ('b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
