# Generated by Django 3.2 on 2021-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210420_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
    ]
