# Generated by Django 3.2 on 2022-01-09 18:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220108_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_views',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220109/'),
        ),
    ]
