# Generated by Django 3.2 on 2021-05-01 20:35

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_photo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_locType1',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_locType2',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_locType3',
            field=models.CharField(default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
