# Generated by Django 3.2 on 2022-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220109_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='b_views',
            field=models.CharField(default='0', max_length=12, null=True),
        ),
    ]
