# Generated by Django 3.2 on 2021-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210501_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_theme',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
