# Generated by Django 3.2 on 2021-05-06 00:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_koreadongpgtbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/20210506/'),
        ),
    ]
