# Generated by Django 3.2 on 2021-05-13 20:48

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrcSido',
            fields=[
                ('doro_cd', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('doro_nm', models.CharField(blank=True, max_length=80, null=True)),
                ('doro_roma', models.CharField(blank=True, max_length=80, null=True)),
                ('dong_one_cd', models.CharField(max_length=2)),
                ('sido_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('sido_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('sigungu_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('sigungu_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_nm', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_roma', models.CharField(blank=True, max_length=40, null=True)),
                ('dong_type', models.CharField(blank=True, max_length=1, null=True)),
                ('dong_cd', models.CharField(blank=True, max_length=3, null=True)),
                ('is_use', models.CharField(blank=True, max_length=1, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=1, null=True)),
                ('change_content', models.CharField(blank=True, max_length=14, null=True)),
                ('from_date', models.CharField(blank=True, max_length=8, null=True)),
                ('to_date', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'entrc_sido',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/20210513/'),
        ),
    ]
