# Generated by Django 3.2 on 2022-03-13 13:43

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_photo_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220313/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='p_id',
            field=models.ForeignKey(blank=True, db_column='p_id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='posts.photo'),
        ),
    ]
