# Generated by Django 3.2 on 2021-05-29 21:53

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210513_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/20210529/'),
        ),
    ]
