# Generated by Django 3.2 on 2022-03-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220313_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='b_text',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='pc_type',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_filename',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_isthumb',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
