# Generated by Django 3.2 on 2021-05-30 11:36

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210529_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/20210530/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.posts'),
        ),
    ]
