# Generated by Django 3.2 on 2022-03-14 09:06

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_photo_p_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='b_id',
            field=models.ForeignKey(blank=True, db_column='b_id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='photo_b_id', to='posts.posts'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220314/'),
        ),
    ]
