# Generated by Django 3.2 on 2021-07-13 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0015_alter_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='filename',
            new_name='p_filename',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='id',
            new_name='p_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20210713/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_del',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='posts',
            name='id',
            field=models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='posts',
            name='p_id',
            field=models.ForeignKey(db_column='p_id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='posts.photo'),
        ),
    ]
