# Generated by Django 3.2 on 2022-03-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220314_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='b_title',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
