# Generated by Django 3.2.5 on 2021-07-25 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0017_alter_photo_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('lp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lp_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('lp_del', models.CharField(default='N', max_length=1)),
                ('b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, to='posts.posts')),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
