# Generated by Django 3.2 on 2022-03-15 18:38

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_posts_b_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KoreaDongPgTbl',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='b_loctype1',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='b_loctype2',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='b_loctype3',
        ),
        migrations.AddField(
            model_name='posts',
            name='b_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_latitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_longtitude',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_place_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220315/'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='b_id',
            field=models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, related_name='postcomment_b_id', to='posts.posts'),
        ),
    ]
