# Generated by Django 3.2 on 2022-03-17 19:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0019_auto_20220315_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220317/'),
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('sp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sp_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='savepost_username', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('sp_b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, related_name='savepost_b_id', to='posts.posts')),
            ],
        ),
    ]
