# Generated by Django 3.2 on 2022-03-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20220317_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savepost',
            old_name='sp_b_id',
            new_name='b_id',
        ),
    ]
