# Generated by Django 3.2 on 2022-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_rename_sp_b_id_savepost_b_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='p_image',
        ),
        migrations.AlterField(
            model_name='photo',
            name='p_filename',
            field=models.CharField(max_length=256),
        ),
    ]
