# Generated by Django 3.2 on 2022-03-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20220320_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_filename',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
