# Generated by Django 3.2 on 2022-04-05 14:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0023_alter_photo_p_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPlace',
            fields=[
                ('pp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pp_place_id', models.TextField()),
                ('pp_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('pp_del', models.CharField(default='N', max_length=1)),
                ('b_id', models.ForeignKey(db_column='b_id', on_delete=django.db.models.deletion.CASCADE, related_name='postplace_b_id', to='posts.posts')),
                ('id', models.ForeignKey(db_column='id', default='', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
