# Generated by Django 3.2 on 2022-04-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_postplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='b_place_id',
            field=models.TextField(null=True),
        ),
    ]
