# Generated by Django 3.2 on 2022-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_posts_b_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postplace',
            name='pp_type',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
