# Generated by Django 3.2 on 2022-04-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_postplace_pp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_update_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
