# Generated by Django 3.2 on 2022-04-30 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_posts_b_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='b_update_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
