# Generated by Django 3.2 on 2022-05-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_posts_b_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepost',
            name='sp_is_noti',
            field=models.BooleanField(default=False),
        ),
    ]
