# Generated by Django 3.2.13 on 2022-06-17 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0034_auto_20220617_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_user_id',
            field=models.ForeignKey(db_column='p_user_id', default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='postplace',
            name='pp_user_id',
            field=models.ForeignKey(db_column='pp_user_id', default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='postplace_user_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
