# Generated by Django 3.2.13 on 2022-06-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20220617_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='b_permit_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_permit_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='b_permit_place',
            field=models.BooleanField(default=True),
        ),
    ]
