# Generated by Django 3.2.13 on 2022-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20220617_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='pc_etc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
