# Generated by Django 3.2.13 on 2022-08-08 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_postcomment_pc_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountUnread',
            fields=[
                ('cu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cu_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('cu_count', models.IntegerField(default=0)),
                ('sp_id', models.ForeignKey(db_column='sp_id', default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='countunread_sp_id', to='posts.savepost')),
            ],
        ),
    ]
