# Generated by Django 3.2 on 2021-05-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoreaDongPgTbl',
            fields=[
                ('adm_dr_cd', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sido_nm', models.CharField(max_length=45)),
                ('sigungu_nm', models.CharField(max_length=45)),
                ('adm_dr_nm', models.CharField(max_length=45)),
                ('sido_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('sigungu_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('adm_dr_nm_eng', models.CharField(blank=True, max_length=45, null=True)),
                ('sido_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('sigungu_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('adm_dr_nm_cn', models.CharField(blank=True, max_length=45, null=True)),
                ('sido_cd', models.CharField(max_length=2)),
                ('sigungu_cd', models.CharField(max_length=5)),
                ('adm_dr_cd2', models.CharField(max_length=11)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'korea_dong_pg_tbl',
                'managed': False,
            },
        ),
    ]
