# Generated by Django 3.2 on 2021-05-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainP', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KoreaDongPgTbl',
        ),
    ]
