# Generated by Django 3.2 on 2022-03-13 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_image', imagekit.models.fields.ProcessedImageField(default='', upload_to='images/profile/20220313/')),
                ('up_imagename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('up_comment', models.CharField(max_length=15, null=True)),
                ('up_id', models.ForeignKey(db_column='up_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('uf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uf_reader', models.ForeignKey(db_column='uf_reader', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('uf_reading', models.ForeignKey(db_column='uf_reading', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
