# Generated by Django 3.2 on 2022-03-08 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='아이디')),
                ('user_email', models.CharField(max_length=30, null=True, verbose_name='이메일')),
                ('user_nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('user_password', models.CharField(max_length=35, verbose_name='비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_image', imagekit.models.fields.ProcessedImageField(default='', upload_to='images/profile/20220308/')),
                ('up_imagename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('up_comment', models.CharField(max_length=15, null=True)),
                ('up_id', models.ForeignKey(db_column='up_id', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
