# Generated by Django 3.2 on 2021-08-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='아이디')),
                ('user_email', models.CharField(max_length=30, null=True, verbose_name='이메일')),
                ('user_nickname', models.CharField(max_length=20, verbose_name='닉네임')),
                ('user_password', models.CharField(max_length=35, verbose_name='비밀번호')),
            ],
        ),
    ]
