# Generated by Django 3.2 on 2022-03-08 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_image', imagekit.models.fields.ProcessedImageField(default='', upload_to='images/20220308/')),
                ('up_imagename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('up_comment', models.CharField(max_length=15, null=True)),
                ('up_id', models.ForeignKey(db_column='up_id', max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
