# Generated by Django 3.2 on 2022-03-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('uf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uf_reader', models.ForeignKey(db_column='uf_reader', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('uf_reading', models.ForeignKey(db_column='uf_reading', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
