# Generated by Django 3.2 on 2021-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=30, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='아이디'),
        ),
    ]
