# Generated by Django 3.2 on 2022-03-08 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='up_id',
            field=models.ForeignKey(max_length=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='up_image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='images/profile/20220308/'),
        ),
    ]
