# Generated by Django 3.2 on 2022-03-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_up_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='up_image',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='up_imagename',
            field=models.CharField(max_length=256, null=True, verbose_name='첨부파일명'),
        ),
    ]
