# Generated by Django 3.2 on 2022-04-14 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_userprofile_up_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='up_id',
            field=models.ForeignKey(db_column='up_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
