# Generated by Django 3.2 on 2022-05-11 21:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_userprofile_up_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFCMToken',
            fields=[
                ('ufcm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ufcm_token', models.CharField(max_length=50)),
                ('ufcm_token_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('ufcm_user_id', models.ForeignKey(db_column='ufcm_user_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='userfcmtoken_id', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
