# Generated by Django 3.2 on 2022-05-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userfcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='ufcm_token',
            field=models.CharField(max_length=200),
        ),
    ]
