# Generated by Django 3.2 on 2022-05-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userfcmtoken_ufcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='ufcm_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
