# Generated by Django 3.2 on 2022-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userfcmtoken_ufcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_device_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
