# Generated by Django 3.2 on 2022-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userfcmtoken_ufcm_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='ufcm_device_id',
            field=models.CharField(max_length=200),
        ),
    ]
