# Generated by Django 3.2 on 2022-05-13 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_userfcmtoken_ufcm_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfcmtoken',
            old_name='ufcm_token_timestamp',
            new_name='ufcm_token_check',
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_fu_c',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_p_c',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_p_u',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_sp_c',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='ufcm_token_expire',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
