# Generated by Django 3.2 on 2022-05-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220513_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfcmtoken',
            old_name='ufcm_token_expire',
            new_name='ufcm_token_add',
        ),
    ]
