# Generated by Django 3.2 on 2022-05-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_usernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotification',
            old_name='un_id',
            new_name='un_token_id',
        ),
    ]
