# Generated by Django 3.2 on 2022-05-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_un_id_usernotification_un_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='un_token_id',
            field=models.ForeignKey(db_column='un_token_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_id', to='users.userfcmtoken'),
        ),
    ]
