# Generated by Django 3.2 on 2022-05-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_usernotification_un_token_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
