# Generated by Django 3.2 on 2022-05-13 17:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0004_auto_20220513_1719'),
        ('users', '0019_delete_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('un_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('un_title', models.CharField(max_length=200, null=True)),
                ('un_body', models.TextField(null=True)),
                ('un_send_date', models.DateField(default=datetime.datetime.now)),
                ('un_is_sended', models.BooleanField(default=True)),
                ('un_is_read', models.BooleanField(default=False)),
                ('un_message_id', models.CharField(max_length=25, null=True)),
                ('un_etc', models.CharField(max_length=100, null=True)),
                ('un_token_id', models.ForeignKey(db_column='un_token_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_id', to='users.userfcmtoken')),
                ('un_type', models.ForeignKey(db_column='un_type', max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_type', to='notis.notitemplate')),
            ],
        ),
    ]
