# Generated by Django 3.2 on 2022-05-15 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0021_auto_20220514_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='un_from',
            field=models.ForeignKey(db_column='un_from', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_from', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='un_to',
            field=models.ForeignKey(db_column='un_to', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_to', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
