# Generated by Django 3.2 on 2022-05-15 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220515_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='un_send_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
