# Generated by Django 3.2 on 2022-05-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_alter_posts_b_update_datetime'),
        ('users', '0024_alter_usernotification_un_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='un_etc',
            field=models.ForeignKey(db_column='un_etc', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernotification_etc', to='posts.posts'),
        ),
    ]
