# Generated by Django 3.2 on 2022-06-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0025_alter_usernotification_un_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('ub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ub_from', models.ForeignKey(db_column='ub_from', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='ub_from', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('ub_to', models.ForeignKey(db_column='ub_to', max_length=12, on_delete=django.db.models.deletion.CASCADE, related_name='ub_to', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
