# Generated by Django 3.2 on 2022-06-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0030_alter_savepost_sp_is_noti'),
        ('users', '0026_userblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotiCount',
            fields=[
                ('unc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unc_count', models.CharField(max_length=2, null=True)),
                ('unc_b_id', models.ForeignKey(db_column='unc_b_id', max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unc_b_id', to='posts.posts')),
                ('unc_user_id', models.ForeignKey(db_column='unc_user_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='unc_user_id', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
