# Generated by Django 3.2 on 2022-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_usernoticount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernoticount',
            name='unc_count',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
