# Generated by Django 3.2 on 2022-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_usernoticount_unc_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernoticount',
            name='unc_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
