# Generated by Django 3.2.13 on 2022-06-16 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0033_posts_b_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.ForeignKey(db_column='id', default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.ForeignKey(db_column='id', default='', max_length=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
