# Generated by Django 3.2.13 on 2022-06-16 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0034_auto_20220616_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='p_user_id',
            field=models.ForeignKey(db_column='p_user_id', default='', max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user_id', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
