# Generated by Django 3.2.13 on 2022-06-16 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0035_auto_20220616_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='p_user_id',
            field=models.ForeignKey(db_column='p_user_id', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='photo_user_id', to='auth.user', to_field='username'),
        ),
    ]
