# Generated by Django 3.2.13 on 2022-06-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_photo_p_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='p_user_id',
        ),
    ]
