# Generated by Django 3.2 on 2022-06-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('rt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rt_text', models.CharField(max_length=100)),
            ],
        ),
    ]
