# Generated by Django 3.2 on 2022-06-12 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0030_alter_savepost_sp_is_noti'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='rt_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('r_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('r_is_resolved', models.BooleanField(default=False)),
                ('r_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('r_b_id', models.ForeignKey(blank=True, db_column='r_b_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_b_id', to='posts.posts')),
                ('r_p_id', models.ForeignKey(blank=True, db_column='r_p_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_p_id', to='posts.photo')),
                ('r_pc_id', models.ForeignKey(blank=True, db_column='r_pc_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_pc_id', to='posts.postcomment')),
                ('r_pp_id', models.ForeignKey(blank=True, db_column='r_pp_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_pp_id', to='posts.postplace')),
                ('r_type', models.ForeignKey(db_column='r_type', max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='r_type', to='reports.reporttemplate')),
                ('r_user_id', models.ForeignKey(blank=True, db_column='r_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_user_id', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
