# Generated by Django 3.2 on 2022-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20220612_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='rt_is_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='rt_type',
            field=models.CharField(max_length=20),
        ),
    ]
