# Generated by Django 3.2 on 2022-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_reporttemplate_rt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='r_typetitle',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
