# Generated by Django 3.2 on 2022-06-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20220612_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='r_report_text',
            field=models.TextField(null=True),
        ),
    ]
