# Generated by Django 3.2 on 2022-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('notitemp_type', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
