# Generated by Django 3.2 on 2022-05-13 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='notitemp_body',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='notitemp_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='notitemp_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
