# Generated by Django 3.2 on 2022-05-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0002_auto_20220513_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationTemplate',
            new_name='NotiTemplate',
        ),
    ]
