# Generated by Django 3.2 on 2022-05-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notis', '0003_rename_notificationtemplate_notitemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notitemplate',
            name='notitemp_body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='notitemplate',
            name='notitemp_type',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
